services:
  db:
    image: postgres:17
    container_name: movie-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movie
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./app.env:/app/cmd/movie/app.env:ro
      - ./app.env:/app/app.env:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d movie"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-app
    ports:
      - "8080:8080"
    env_file:
      - app.env
    environment:
      - FFMPEG_BIN=/usr/bin/ffmpeg
    volumes:
      - ./uploads:/app/uploads
      - ./hls:/app/hls
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:

